"""
visual.py
This file will take in the parameters generated by either our or the KITRO model and generate a 3D mesh image.
This will be an easy way to do this, because it is not easy to do this in the original KITRO code.
"""

import os
import numpy as np
import trimesh
from PIL import Image

os.environ["PYOPENGL_PLATFORM"] = "osmesa"
SAVE_DIR = "logs\images"
os.makedirs(SAVE_DIR, exist_ok=True)

# Flip Y and Z coords of vertices from SMPL output to appear upright and front-facing.
flip_yz = np.asarray([
    [1,  0,  0, 0],
    [0, -1,  0, 0],
    [0,  0, -1, 0],
    [0,  0,  0, 1]
])

def render_mesh_img(verts, faces, file_name=None):
    mesh = trimesh.Trimesh(vertices=verts, faces=faces, process=False)
    mesh.apply_transform(flip_yz)

    scene = trimesh.Scene(mesh)
    png_raw = scene.save_image(resolution = (512,512), visible = False)
    img = Image.open(trimesh.util.wrap_as_stream(png_raw)).convert("RGB")

    if file_name is None:
        return img
    else:
        file_path = os.path.join(SAVE_DIR, file_name)
        img.save(file_path)

def render_mesh_gif(vertices, faces, file_name):
    file_path = os.path.join(SAVE_DIR, file_name)
    images = []

    for i in range(len(vertices)):
        verts = vertices[i].cpu().numpy()
        img = render_mesh_img(verts, faces)
        images.append(img)
        
    images[0].save(
        file_path,
        save_all = True,
        append_images = images[1:],
        duration = 100,
        loop = 0
    )