"""
visual.py
This file will take in the parameters generated by either our or the KITRO model and generate a 3D mesh image.
This will be an easy way to do this, because it is not easy to do this in the original KITRO code.
"""

import os
import numpy as np
import trimesh
from PIL import Image

SAVE_DIR = "logs\images"
os.makedirs(SAVE_DIR, exist_ok=True)

def render_mesh(vertices, faces, file_name):
    mesh = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)
    flip_yz = np.diag([1, -1, -1, 1])
    mesh.apply_transform(flip_yz)
    
    scene = trimesh.Scene(mesh)
    image = scene.save_image(resolution=(512, 512), visible=True)

    file_path = os.path.join(SAVE_DIR, file_name)
    with open(file_path, "wb") as f:
        f.write(image)