"""
visual.py
This file will take in the paraeters generated by either our or the KITRO model and generate a 3D mesh image.
This will be an easy way to do this, because it is not easy to do this in the original KITRO code.
"""
